# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    image: boletin_production_postgres
    container_name: boletin_local_postgres
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - boletin_postgres_data:/var/lib/postgresql/data
      - boletin_data_backups:/backups
    ports:
      - 5434:5432

volumes:
  boletin_postgres_data:
  boletin_data_backups:


