# Generated by Django 4.1.13 on 2024-01-30 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_marca_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tipo_vehiculo',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('AZUL', 'Azul')], default='ROJO', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_baja',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 12, 54, 33, 358416, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_fabricacion',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 12, 54, 38, 900964, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_matriculacion',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 12, 54, 42, 346071, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='suspendido',
            field=models.BooleanField(default=False),
        ),
    ]
