# Generated by Django 4.1.13 on 2024-02-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0003_rename_tipo_vehiculo_vehiculo_tipo_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('COCH', 'Coche'), ('CICL', 'Ciclomotor'), ('MOTO', 'Motocicleta')], max_length=4),
        ),
    ]
